name: rollanddice
description: rollanddice
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  get_it: 5.0.1
  provider_architecture: 1.0.3
  intl: 0.16.1
  page_transition: 1.1.7+2
  flutter_svg: 0.19.0
  carousel_slider: 2.3.1
  fimber: 0.4.4
  flushbar: 1.10.4
  shared_preferences: 0.5.11
  package_info: 0.4.3
  connectivity: 0.4.5+3
  firebase_auth: 0.20.0+1
  cloud_firestore: 0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:


# The following section is specific to Flutter.
flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Celias
      fonts:
        - asset: assets/fonts/Celias.ttf
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
    